const producto = [{
    id: "1",
    categoria: "Colmi",
    descripcion:"Blablabla",
    nombre: "Colmi s7",
    precio: "30.000",
    img:"C:\Users\karae\Desktop\javascrip\Imagenes\Xiaomi\Galaxy Watch 4.webp",
},
{
    id: "1",
    categoria: "Colmi",
    descripcion:"Blablabla",
    nombre: "Colmi s7",
    precio: "30.000",
    img:"C:\Users\karae\Desktop\javascrip\Imagenes\Xiaomi\Galaxy Watch 4.webp",
},
{id: "1",
    categoria: "Colmi",
    descripcion:"Blablabla",
    nombre: "Colmi s7",
    precio: "30.000",
    img:"C:\Users\karae\Desktop\javascrip\Imagenes\Xiaomi\Galaxy Watch 4.webp",
},
]
//los objetos se separan por comas//